import type { NextPage } from "next";
import Head from "next/head";
import "react-alice-carousel/lib/alice-carousel.css";
import AliceCarousel from "react-alice-carousel";
import Image from "next/image";
import test1 from "/public/static/home/1.jpg";
import test2 from "/public/static/home/2.jpg";
import test3 from "/public/static/home/3.jpg";
import "react-alice-carousel/lib/alice-carousel.css";
import { trpc } from "../utils/trpc";
import { useCallback, useEffect, useRef } from "react";
import { useRouter } from "next/router";


const Home: NextPage = () => {
  const payMutation = trpc.useMutation(["example.hello"]);
  const router = useRouter();
  const myEl = useRef(null);

  const onPay = useCallback(() => {
    payMutation.mutate({
      text: "sda",
    })
  }, []);

  useEffect(() => {
     
    if(payMutation.data?.htm){
(myEl.current as unknown as HTMLElement).getElementsByTagName("form")[0]?.submit();
    }
  
  }, [payMutation.isSuccess]);


if(payMutation.data){
  return <div ref={myEl} dangerouslySetInnerHTML={{ __html: payMutation.data?.htm.toString() }} />
}
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-full bg-stone-100 flex flex-col p-3">
        <button onClick={() => onPay()}>pay here</button>
        
        <div className="bgPaper  h-64 "></div>
      </main>
    </>
  );
};

export default Home;
